backend:
  name: github
  # change repo to your git repository url
  repo: injoon5/gatsby-starter-apple

media_folder: src/posts/blog/images
public_folder: /blog/images

collections:
  - name: blog
    label: Blog
    folder: src/posts/blog
    slug: '{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - label: Slug
        name: slug
        widget: text
        required: true
      - label: Title
        name: title
        widget: text
        required: true
      - label: "Date, Time"
        name: "date"
        widget: "datetime"
      - label: Category
        name: category
        widget: text
        required: false
      - label: Description
        name: desc
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
      - label: Alt
        name: alt
        widget: text
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
